databases:
  - name: my-tubes-db
    plan: basic-256mb
    databaseName: mytubesdb
    user: mytubesdb_user

services:
  - type: web
    plan: starter
    name: mytubesapi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn app.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mytubesdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4