# Generated by Django 4.2.4 on 2025-07-12 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video_url", models.URLField()),
                ("video_image_url", models.URLField(blank=True, null=True)),
                ("last_sync", models.DateTimeField(default=django.utils.timezone.now)),
                ("upload_time", models.DateTimeField()),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload",
                        to="core.subscription",
                    ),
                ),
            ],
        ),
    ]
