# Generated by Django 4.2.4 on 2024-03-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
