# Generated by Django 4.2.4 on 2024-04-09 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscriptioncollection",
            name="last_data_sync",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
