# Generated by Django 4.2.4 on 2024-08-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_group_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="emoji",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
