# Generated by Django 4.2.4 on 2024-10-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_group_emoji"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="instagram_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="youtube_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
