# Generated by Django 4.2.4 on 2024-03-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_group_subscription_usersubscriptionlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscriptionlist",
            name="subscriptions",
            field=models.ManyToManyField(
                related_name="subscription_lists", to="core.subscription"
            ),
        ),
    ]
