# Generated by Django 4.2.4 on 2024-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_group_is_public_profile_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
