# Generated by Django 4.2.4 on 2025-02-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_group_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telegram_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tiktok_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
